[project]
name = "qt-repl"
version = "0.1.0"
description = "Учебный эмулятор командной оболочки UNIX с GUI на PyQt6 и виртуальной ФС"
readme = "README.md"
authors = [
    { name = "Arthur", email = "baginian.artur@yandex.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pyqt6>=6.11.0",
]

[project.scripts]
repl = "repl:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "repl"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]

[tool.ruff]
line-length = 80
src = ["src", "tests"]

[tool.ruff.lint]
preview = true
select = ["E", "F", "W", "C901", "N", "D", "PLR0913", "PLR0917", "PLR2004"]
ignore = ["D203", "D213"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pylint]
max-args = 7
max-positional-args = 7

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D102", "D103"]
